name: informatik_projekt
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.3.10
  flutter_icons: ^1.0.0+1
  fl_chart: ^0.12.2
  material_floating_search_bar: ^0.2.6
  implicitly_animated_reorderable_list: ^0.2.5
  material_design_icons_flutter: ^4.0.5345
  provider: ^4.3.1
  syncfusion_flutter_charts: ^18.4.35
  change_app_package_name: ^0.1.2
  animations: ^1.1.2
  sizer: ^1.1.8
  flutter_advanced_switch: ^0.0.9+3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+1
  cloud_firestore: ^0.14.1+1
  flutter_local_notifications: ^4.0.0
  shared_preferences: ^0.5.12+4
  fading_edge_scrollview: ^1.1.4
  page_transition: ^1.1.7+6



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
